# =========================================================
# CRE PROJECT SETTINGS FILE
# =========================================================

rpcs:
  - chain-name: ethereum-testnet-sepolia
    url: http://127.0.0.1:8545
